services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ${DATA_MYSQL_PATH}:/var/lib/mysql

    healthcheck:
      test: '/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SELECT 1;"'
      interval: 1s
      timeout: 10s
      retries: 10

  crawler:
    build:
      context: .
      dockerfile: apps/crawler/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      frontend:
        condition: service_started
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"

    healthcheck:
      test: "curl --fail http://phpmyadmin"
      interval: 60s
      timeout: 10s
      retries: 5

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}
      - UPLOAD_LIMIT=1G
      - HIDE_PHP_VERSION=true
